## Data and Digital Skills - Enrich Data with Python Libraries
#### Antrang Agrawal

## Agenda:
- ##### **Data Maniupation**: Pandas, Dask
- ##### **Data Visaulization**: Streamlit, Seaborn
- ##### **Text Processing**: TheFuzz

## Install and Import Libraries

To use the functions and methods in pandas, we need to first install these libraries in our environment.

In [ ]:
!pip install pandas numpy openpyxl streamlit pygwalker thefuzz requests

In [21]:
import pandas as pd # import the pandas library and provide an alias or shorthand name for the imported library/module
import numpy as np
import requests
import warnings

warnings.filterwarnings('ignore')

## Section 1: Data Manipulation using Pandas

We will begin by introducing the `Series`, `DataFrame`, and `Index` classes, which are the basic building blocks of the pandas library, and showing how to work with them. By the end of this section, you will be able to create DataFrames and perform operations on them to inspect and filter the data.

## Creating DataFrames

We can create DataFrames from a variety of sources such as other Python objects, flat files, webscraping, and API requests. Here, we will see just a couple of examples, but be sure to check out [this page](https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html) in the documentation for a complete list.

#### Using a CSV (Comma-Seperated Values) file

In [4]:
import pandas as pd

meteorites = pd.read_csv("./meteorites.csv")
meteorites

,name,id,name_type,class,mass,fall,year,lat,long,geolocation
0,Aachen,1,Valid,L5,21.0,Fell,1880.0,50.77500,6.08333,"(50.775, 6.08333)"
1,Aarhus,2,Valid,H6,720.0,Fell,1951.0,56.18333,10.23333,"(56.18333, 10.23333)"
2,Abee,6,Valid,EH4,107000.0,Fell,1952.0,54.21667,-113.00000,"(54.21667, -113.0)"
3,Acapulco,10,Valid,Acapulcoite,1914.0,Fell,1976.0,16.88333,-99.90000,"(16.88333, -99.9)"
4,Achiras,370,Valid,L6,780.0,Fell,1902.0,-33.16667,-64.95000,"(-33.16667, -64.95)"
...,...,...,...,...,...,...,...,...,...,...
45711,Zillah 002,31356,Valid,Eucrite,172.0,Found,1990.0,29.03700,17.01850,"(29.037, 17.0185)"
45712,Zinder,30409,Valid,"Pallasite, ungrouped",46.0,Found,1999.0,13.78333,8.96667,"(13.78333, 8.96667)"
45713,Zlin,30410,Valid,H4,3.3,Found,1939.0,49.25000,17.66667,"(49.25, 17.66667)"
45714,Zubkovsky,31357,Valid,L6,2167.0,Found,2003.0,49.78917,41.50460,"(49.78917, 41.5046)"
45715,Zulu Queen,30414,Valid,L3.7,200.0,Found,1976.0,33.98333,-115.68333,"(33.98333, -115.68333)"

#### Using a Excel (.xlsx, .xls) file

In [48]:
financials = pd.read_excel("./data.xlsx",sheet_name="rawdata")
financials

    Year published
0          1600(1)
1          1655(1)
2          1705(1)
3          1709(1)
4          1748(1)
..             ...
101       1945(10)
102        1946(4)
103        1947(5)
104        1948(6)
105        1949(3)

[106 rows x 1 columns]

#### Using Data from an API

In [6]:
import requests

response = requests.get(
    'https://data.nasa.gov/resource/gh4g-9sfh.json',
    params={'$limit': 50_000},
    verify=False
)

if response.ok:
    payload = response.json()
else:
    print(f'Request was not successful and returned code: {response.status_code}.')
    payload = None

/Users/antrangagrawal/.pyenv/versions/3.11.8/lib/python3.11/site-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host '127.0.0.1'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Request was not successful and returned code: 404.

## Inspecting the data

Now that we have some data, we need to perform an initial inspection of it. This gives us information on what the data looks like, how many rows/columns there are, and how much data we have.

#### How many rows and columns are there?

In [5]:
meteorites.shape

(45716, 10)

#### What are the column names?

In [6]:
meteorites.columns

Index(['name', 'id', 'name_type', 'class', 'mass', 'fall', 'year', 'lat',
       'long', 'geolocation'],
      dtype='object')

#### What type of data does each column currently hold?
- **Integers** : uint64, int32, int64
- **Decimals** : float32, float64
- **Text** : string, string[python]
- **Others** : object

In [11]:
meteorites.dtypes

name            object
id               int64
name_type       object
class           object
mass           float64
fall            object
year           float64
lat            float64
long           float64
geolocation     object
dtype: object

#### What does the data look like?

In [12]:
meteorites.head() # First 5 Rows

,name,id,name_type,class,mass,fall,year,lat,long,geolocation
0,Aachen,1,Valid,L5,21.0,Fell,1880.0,50.77500,6.08333,"(50.775, 6.08333)"
1,Aarhus,2,Valid,H6,720.0,Fell,1951.0,56.18333,10.23333,"(56.18333, 10.23333)"
2,Abee,6,Valid,EH4,107000.0,Fell,1952.0,54.21667,-113.00000,"(54.21667, -113.0)"
3,Acapulco,10,Valid,Acapulcoite,1914.0,Fell,1976.0,16.88333,-99.90000,"(16.88333, -99.9)"
4,Achiras,370,Valid,L6,780.0,Fell,1902.0,-33.16667,-64.95000,"(-33.16667, -64.95)"

#### Sometimes there may be extraneous data at the end of the file, so checking the bottom few rows is also important:

In [13]:
meteorites.tail() # Last 5 Rows

,name,id,name_type,class,mass,fall,year,lat,long,geolocation
45711,Zillah 002,31356,Valid,Eucrite,172.0,Found,1990.0,29.03700,17.01850,"(29.037, 17.0185)"
45712,Zinder,30409,Valid,"Pallasite, ungrouped",46.0,Found,1999.0,13.78333,8.96667,"(13.78333, 8.96667)"
45713,Zlin,30410,Valid,H4,3.3,Found,1939.0,49.25000,17.66667,"(49.25, 17.66667)"
45714,Zubkovsky,31357,Valid,L6,2167.0,Found,2003.0,49.78917,41.50460,"(49.78917, 41.5046)"
45715,Zulu Queen,30414,Valid,L3.7,200.0,Found,1976.0,33.98333,-115.68333,"(33.98333, -115.68333)"

#### Get some information about the DataFrame

In [14]:
meteorites.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45716 entries, 0 to 45715
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         45716 non-null  object
 1   id           45716 non-null  int64
 2   name_type    45716 non-null  object
 3   class        45716 non-null  object
 4   mass         45585 non-null  float64
 5   fall         45716 non-null  object
 6   year         45425 non-null  float64
 7   lat          38401 non-null  float64
 8   long         38401 non-null  float64
 9   geolocation  38401 non-null  object
dtypes: float64(4), int64(1), object(5)
memory usage: 3.5+ MB

## Extracting Subsets

A crucial part of working with DataFrames is extracting subsets of the data: finding rows that meet a certain set of criteria, isolating columns/rows of interest, etc. After narrowing down our data, we are closer to discovering insights. This section will be the backbone of many analysis tasks.

#### Selecting columns

We can select columns as attributes if their names would be valid Python variables:

In [16]:
meteorites.name

0            Aachen
1            Aarhus
2              Abee
3          Acapulco
4           Achiras
            ...
45711    Zillah 002
45712        Zinder
45713          Zlin
45714     Zubkovsky
45715    Zulu Queen
Name: name, Length: 45716, dtype: object

If they aren't, we have to select them as keys. However, we can select multiple columns at once this way:

In [18]:
meteorites['name']

0            Aachen
1            Aarhus
2              Abee
3          Acapulco
4           Achiras
            ...
45711    Zillah 002
45712        Zinder
45713          Zlin
45714     Zubkovsky
45715    Zulu Queen
Name: name, Length: 45716, dtype: object

In [23]:
meteorites[['name','class']]

             name                 class
0          Aachen                    L5
1          Aarhus                    H6
2            Abee                   EH4
3        Acapulco           Acapulcoite
4         Achiras                    L6
...           ...                   ...
45711  Zillah 002               Eucrite
45712      Zinder  Pallasite, ungrouped
45713        Zlin                    H4
45714   Zubkovsky                    L6
45715  Zulu Queen                  L3.7

[45716 rows x 2 columns]

#### Selecting rows

In [26]:
meteorites[100:104]

,name,id,name_type,class,mass,fall,year,lat,long,geolocation
100,Benton,5026,Valid,LL6,2840.0,Fell,1949.0,45.95000,-67.55000,"(45.95, -67.55)"
101,Berduc,48975,Valid,L6,270.0,Fell,2008.0,-31.91000,-58.32833,"(-31.91, -58.32833)"
102,Béréba,5028,Valid,Eucrite-mmict,18000.0,Fell,1924.0,11.65000,-3.65000,"(11.65, -3.65)"
103,Berlanguillas,5029,Valid,L6,1440.0,Fell,1811.0,41.68333,-3.80000,"(41.68333, -3.8)"

#### Filtering based on a Condition

In [37]:
meteorites[meteorites['class'] == 'L6']

,name,id,name_type,class,mass,fall,year,lat,long,geolocation
4,Achiras,370,Valid,L6,780.0,Fell,1902.0,-33.16667,-64.95000,"(-33.16667, -64.95)"
8,Aguada,398,Valid,L6,1620.0,Fell,1930.0,-31.60000,-65.23333,"(-31.6, -65.23333)"
11,Aïr,424,Valid,L6,24000.0,Fell,1925.0,19.08333,8.38333,"(19.08333, 8.38333)"
13,Akaba,426,Valid,L6,779.0,Fell,1949.0,29.51667,35.05000,"(29.51667, 35.05)"
24,Aleppo,462,Valid,L6,3200.0,Fell,1873.0,36.23333,37.13333,"(36.23333, 37.13333)"
...,...,...,...,...,...,...,...,...,...,...
45671,Yayjinna,30359,Valid,L6,262.5,Found,1965.0,-32.03333,126.17500,"(-32.03333, 126.175)"
45673,Yelland 001,54765,Valid,L6,4.5,Found,2011.0,39.55801,-114.42715,"(39.55801, -114.42715)"
45681,York (stone),30368,Valid,L6,1440.0,Found,1928.0,40.86667,-97.60000,"(40.86667, -97.6)"
45710,Zillah 001,31355,Valid,L6,1475.0,Found,1990.0,29.03700,17.01850,"(29.037, 17.0185)"
45714,Zubkovsky,31357,Valid,L6,2167.0,Found,2003.0,49.78917,41.50460,"(49.78917, 41.5046)"

Important: Take note of the syntax here. We surround each condition with parentheses, and we use bitwise operators (&, |, ~) instead of logical operators (and, or, not).

## Data Cleaning

#### Renaming Columns

In [42]:
meteorites.rename({},inplace=True)

class
L6          8339
H5          7164
L5          4817
H6          4529
H4          4222
            ...
CH/CBb         1
H/L~4          1
LL3.7-6        1
H3.7/3.8       1
L/LL           1
Name: count, Length: 455, dtype: int64

#### Dropping NA Columns

In [ ]:
meteorites.dropna(,inplace=True)

#### Dropping Duplicate Rows

In [ ]:
meteorites.drop_duplicates(,inplace=True)

#### Dropping Columns

In [ ]:
meteorites.drop(,inplace=True)

#### Typing Conversion

In [ ]:
meteorites['name'] = meteorites['name'].astype(string)

## Aggregations and Grouping

In [51]:
#### Pivot Tables

In [ ]:
meteorites.pivot_table()

In [ ]:
#### Melting

In [ ]:
meteorites.melt()

In [ ]:
#### Grouping By

In [ ]:
meteorites.groupby()

In [ ]:
#### Merging

In [ ]:
meteorites.merge()

## Section 2: Data Visualization using Seaborn and Streamlit

## Section 3: Text Processing using TheFuzz